#include "gevmcc.h"
#include "gams_option.h"

const char * const gams_option_name[] = {
   gevAlgFileType,
   gevGamsVersion,
   gevLogOption,
   gevReform,
   gevIDEFlag,
   gevDomLim,
   gevIterLim,
   gevNodeLim,
   gevSysOut,
   gevInteger1,
   gevInteger2,
   gevInteger3,
   gevInteger4,
   gevInteger5,
   gevGenSolver,
   gevCurSolver,
   gevPageWidth,
   gevPageSize,
   gevKeep,
   gevThreadsRaw,
   gevFDOpt,
   gevOptCR,
   gevOptCA,
   gevResLim,
   gevWorkSpace,
   gevWorkFactor,
   gevCutOff,
   gevUseCutOff,
   gevCheat,
   gevUseCheat,
   gevTryInt,
   gevReal1,
   gevReal2,
   gevReal3,
   gevReal4,
   gevReal5,
   gevHeapLimit,
   gevFDDelta,
   gevNameCtrFile,
   gevNameLogFile,
   gevNameStaFile,
   gevNameScrDir,
   gevNameGamsDate,
   gevNameGamsTime,
   gevNameSysDir,
   gevNameWrkDir,
   gevNameCurDir,
   gevLicense1,
   gevLicense2,
   gevLicense3,
   gevLicense4,
   gevLicense5,
   gevNameMatrix,
   gevNameInstr,
   gevNameParams,
   gevNameScrExt,
   gevNameScenFile,
   gevNameExtFFile
};

const unsigned gms_optname_len = sizeof(gams_option_name)/sizeof(*gams_option_name);
