test-leg:
  stage: test
  tags: [linux]
  image:
    name: $MACHINES_CONTAINER_REG/leg/builder-full:latest
    entrypoint: [""]
  needs: [fetch-ci-scripts,build-leg]
  script:
    - ctest --test-dir build/test --output-junit doctest_results_linux.xml || ctest --test-dir build/test --rerun-failed --output-on-failure
  artifacts:
    name: unittest-results-linux
    paths: [build/test/doctest_results_linux.xml]
    reports:
      junit: build/test/doctest_results_linux.xml

test-deg:
  stage: test
  tags: [macos]
  needs: [fetch-ci-scripts,build-deg]
  script:
    - ctest --test-dir build/test --output-junit doctest_results_deg.xml || ctest --test-dir build/test --rerun-failed --output-on-failure
  artifacts:
    name: unittest-results-deg
    paths: [build/test/doctest_results_deg.xml]
    reports:
      junit: build/test/doctest_results_deg.xml

test-dac:
  stage: test
  tags: [macos-arm64]
  needs: [fetch-ci-scripts,build-dac]
  script:
    - ctest --test-dir build/test --output-junit doctest_results_dac.xml || ctest --test-dir build/test --rerun-failed --output-on-failure
  artifacts:
    name: unittest-results-dac
    paths: [build/test/doctest_results_dac.xml]
    reports:
      junit: build/test/doctest_results_dac.xml

test-wei:
  stage: test
  tags: [windows]
  image:
    name: $MACHINES_CONTAINER_REG/wei/builder-full:latest
  needs: [fetch-ci-scripts,build-wei]
  script:
    - ctest --test-dir build/test --output-junit doctest_results_windows.xml -E tree
  artifacts:
    name: unittest-results-windows
    paths: [build/test/doctest_results_windows.xml]
    reports:
      junit: build/test/doctest_results_windows.xml
