build-leg:
  stage: build
  tags: [puma]
  image:
    name: $MACHINES_CONTAINER_REG/leg/builder-devel:latest
    entrypoint: [""]
  script:
    - !reference [.get-gams]
    - !reference [.gams-folder-leg]
    - export PATH="/cache/gams-installs/$(cat gams_folder_leg.txt):$HOME/.local/bin:$PATH"
    - cmake -B build -DCMAKE_BUILD_TYPE=Release -S .
    - cmake --build build -v 2>&1 | tee build_log.txt
    - cmake --install build -v
    - python3 ciscripts/report_for_log.py gcc build_log.txt warnings.xml
  needs: [fetch-ci-scripts]
  artifacts:
    name: reshop-leg
    expire_in: 2 hours
    paths: [warnings.xml,build/*.so,build/test,build/gams,build/output]
    reports:
      junit: warnings.xml

build-debug-leg:
  stage: build
  tags: [puma]
  image:
    name: $MACHINES_CONTAINER_REG/leg/builder-devel:latest
    entrypoint: [""]
  script:
    - !reference [.get-gams]
    - !reference [.gams-folder-leg]
    - export PATH="/cache/gams-installs/$(cat gams_folder_leg.txt):$HOME/.local/bin:$PATH"
    - cmake -B build -DCMAKE_BUILD_TYPE=Debug -S .
    - cmake --build build -v 2>&1 | tee build_log.txt
    - cmake --install build -v
    - python3 ciscripts/report_for_log.py gcc build_log.txt warnings.xml
  needs: [fetch-ci-scripts]
  artifacts:
    name: reshop-debug-leg
    expire_in: 2 hours
    paths: [warnings.xml,build/*.so,build/test,build/gams,build/output]
    reports:
      junit: warnings.xml

deg-cleanup:
  stage: build
  tags: [clarus]
  variables:
    GIT_STRATEGY: none
  before_script:
    - chmod +Rw gamsdir
    - rm -rf gamsdir
  script:
    - echo "DONE"

dac-cleanup:
  stage: build
  tags: [macos-arm64]
  variables:
    GIT_STRATEGY: none
  before_script:
    - chmod +Rw gamsdir
    - rm -rf gamsdir
  script:
    - echo "DONE"

build-deg:
  stage: build
  tags: [clarus]
  script:
    - !reference [.get-gams]
    - !reference [.gams-folder-deg]
    - export PATH="$HOME/cache/gams-installs/$(cat gams_folder_deg.txt):$PATH"
    - cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc -S .
    - cmake --build build -v 2>&1 | tee build_log.txt
    - cmake --install build -v
    - python3 ciscripts/report_for_log.py gcc build_log.txt warnings.xml
  needs: [fetch-ci-scripts,deg-cleanup]
  artifacts:
    name: reshop-deg
    expire_in: 2 hours
    paths: [warnings.xml,build/*.dylib,build/test,build/gams,build/output]
    reports:
      junit: warnings.xml

build-dac:
  stage: build
  tags: [macos-arm64]
  script:
    - !reference [.get-gams]
    - !reference [.gams-folder-dac]
    - export PATH="$HOME/cache/gams-installs/$(cat gams_folder_dac.txt):$PATH"
    - cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -S .
    - cmake --build build -v 2>&1 | tee build_log.txt
    - cmake --install build -v
    - python3 ciscripts/report_for_log.py clang build_log.txt warnings.xml
  needs: [fetch-ci-scripts,dac-cleanup]
  allow_failure: true
  artifacts:
    name: reshop-dac
    paths: [warnings.xml,build/*.dylib,build/test,build/gams,build/output]
    expire_in: 2 hours
    reports:
      junit: warnings.xml

build-wei:
  stage: build
  tags: [pond]
  image:
    name: $MACHINES_CONTAINER_REG/wei/builder-full:latest
  script:
    - !reference [.get-gams-wei]
    - !reference [.gams-folder-wei]
    - $gmsdirname = Get-Content mygmsdir.tmp -Raw
    - $GAMS_PATH = "C:\Cache\gams-installs\$gmsdirname"
    - $env:Path = "$GAMS_PATH;$GAMS_PATH\gbin;" + $env:Path
    - cmake -B build -DCMAKE_BUILD_TYPE=Release -G Ninja -DCMAKE_C_COMPILER=icx-cl -S .
    - cmake --build build -v | Tee-Object -FilePath 'build_log.txt'
    - cmake --install build -v
    - python ciscripts/report_for_log.py icl build_log.txt warnings.xml
  needs: [fetch-ci-scripts]
  allow_failure: true
  artifacts:
    name: reshop-wei
    expire_in: 2 hours
    paths: [warnings.xml,build/*.dll,build/*.lib,build/test,build/gams,build/output]
    reports:
      junit: warnings.xml
