test-leg:
  stage: test
  tags: [puma]
  image:
    name: $MACHINES_CONTAINER_REG/leg/builder-devel:latest
    entrypoint: [""]
  needs: [fetch-ci-scripts,build-leg]
  script:
    - !reference [ .get-gams ]
    - !reference [ .gams-folder-leg ]
    - EXPORT GAMSDIR="/cache/gams-installs/$(cat gams_folder_leg.txt)"
    - export PATH="$GAMSDIR:$PATH"
    - ctest --test-dir build/test --output-junit doctest_results_linux.xml || ctest --test-dir build/test --rerun-failed --output-on-failure
    - cp build/* "$GAMSDIR"/
    - bash test/gams/test.sh
    - mkdir emplib && cd emplib && emplib goempgo
    - gams goempgo lo=2 --solver=reshop
    - (tail -n 1 failures_emp.gms | grep -q "Failed tests: 0" && echo "emplib: SUCCESS"); cd ..
    - mkdir quality && cd quality && testlib quality
    - gams quality lo=2 --solver=reshop
    - (tail -n 1 failures_qa.gms | grep -q "Failed tests: 0" && echo "quality: SUCCESS"); cd ..
  artifacts:
    name: unittest-results-linux
    paths: [build/test/doctest_results_linux.xml]
    reports:
      junit: build/test/doctest_results_linux.xml

test-debug-leg:
  stage: test
  tags: [puma]
  image:
    name: $MACHINES_CONTAINER_REG/leg/builder-devel:latest
    entrypoint: [""]
  needs: [fetch-ci-scripts,build-debug-leg]
  script:
    - !reference [ .get-gams ]
    - !reference [ .gams-folder-leg ]
    - ctest --test-dir build/test --output-junit doctest_results_linux.xml || ctest --test-dir build/test --rerun-failed --output-on-failure
  artifacts:
    name: unittest-results-debug-linux
    paths: [build/test/doctest_results_linux.xml]
    reports:
      junit: build/test/doctest_results_linux.xml

test-deg:
  stage: test
  tags: [clarus]
  needs: [fetch-ci-scripts,build-deg]
  script:
    - ctest --test-dir build/test --output-junit doctest_results_deg.xml || ctest --test-dir build/test --rerun-failed --output-on-failure
  artifacts:
    name: unittest-results-deg
    paths: [build/test/doctest_results_deg.xml]
    reports:
      junit: build/test/doctest_results_deg.xml

test-dac:
  stage: test
  tags: [macos-arm64]
  needs: [fetch-ci-scripts,build-dac]
  script:
    - ctest --test-dir build/test --output-junit doctest_results_dac.xml || ctest --test-dir build/test --rerun-failed --output-on-failure
  artifacts:
    name: unittest-results-dac
    paths: [build/test/doctest_results_dac.xml]
    reports:
      junit: build/test/doctest_results_dac.xml

test-wei:
  stage: test
  tags: [pond]
  image:
    name: $MACHINES_CONTAINER_REG/wei/builder-full:latest
  needs: [fetch-ci-scripts,build-wei]
  script:
    - !reference [ .get-gams-wei ]
    - !reference [ .gams-folder-wei ]
    - ctest --test-dir build/test --output-junit doctest_results_windows.xml -E tree
  artifacts:
    name: unittest-results-windows
    paths: [build/test/doctest_results_windows.xml]
    reports:
      junit: build/test/doctest_results_windows.xml
