IMPORT_FUNC(int,License_SetString,char *)
IMPORT_FUNC(void*,MCP_Create,int, int)
IMPORT_FUNC(void,MCP_Destroy,void *)
IMPORT_FUNC(int*,MCP_GetB,void *)
IMPORT_FUNC(double*,MCP_GetX,void *)
IMPORT_FUNC(double*,MCP_GetF,void *)
IMPORT_FUNC(void,MCP_SetInterface,void *, void *)
IMPORT_FUNC(void,MCP_SetPresolveInterface,void *, void *)
IMPORT_FUNC(void,MCP_Jacobian_Structure_Constant,void *, int)
IMPORT_FUNC(void,MCP_Jacobian_Data_Contiguous,void *, int)
IMPORT_FUNC(void,MCP_Jacobian_Diagonal,void*, int)
IMPORT_FUNC(void,MCP_Jacobian_Diagonal_First,void *, int)
IMPORT_FUNC(void*,Options_Create,void)
IMPORT_FUNC(void,Options_Destroy,void *)
IMPORT_FUNC(void,Output_Default,void)
IMPORT_FUNC(void,Output_SetInterface,void *)
IMPORT_FUNC(int,Options_Set,void*,char *)
IMPORT_FUNC(int,Options_SetBoolean,void *,char *,int)
IMPORT_FUNC(int,Options_SetInt,void *,char *,int)
IMPORT_FUNC(int,Options_SetDouble,void *,char *,double)
IMPORT_FUNC(int,Options_SetOther,void *,char *,int)
IMPORT_FUNC(void,Options_Default,void *)
IMPORT_FUNC(void,Options_Display,void *)
IMPORT_FUNC(void,Options_Read,void *, char *)
IMPORT_FUNC(void,Path_AddOptions,void *)
IMPORT_FUNC(int,Path_CheckLicense,int, int)
IMPORT_FUNC(void,Path_Create,int, int)
IMPORT_FUNC(void,Path_Destroy,void)
IMPORT_FUNC(void,Path_SetProblemClass,void *, unsigned char)
IMPORT_FUNC(int,Path_Solve,void *, void *)
IMPORT_FUNC(char*,Path_Version,void)
