set(Python3_INCLUDE_DIRS /scratch/miniconda/3.8/include/python3.8/)
set(Python3_NumPy_INCLUDE_DIRS /scratch/miniconda/3.8/lib/python3.8/site-packages/numpy/core/include)
set(Python3_SOABI cpython-38-darwin)
set(Python3_LINK_OPTIONS -undefined dynamic_lookup)
set(Python3_platform "macosx_10_9_x86_64")
